### ISSUE TITLE
Create a difference map b/w tourists and locals

### ISSUE THREAD

**Issue by jamiecmontgomery** [OHI-Science/sb_sense_of_place#7]
Rather than two mirrored maps of tourists and locals, create a difference map

**Comment by jamiecmontgomery** [comment]
Pretty cool. Tourists love the wharf and the waterfront. But locals light up state st!

The following map shows areas that have more tweets from locals (orange) or tourists (purple). Note the values indicate the log of the absolute difference between number of tweets from each user group. If a hex is purple and has a value of 2.302585, this means there are 10 more tweets from tourists than locals at that location (log of 10 = 2.302585).

![image](https://user-images.githubusercontent.com/6842510/75831926-bd791600-5d69-11ea-8f97-b76896fd8a3c.png)

**Comment by oharac** [comment]
Super cool!  I’d switch to log10() instead of log() for easier to interpret values ie a 1 means 10x the tweets from tourists (would not affect the color ramp)

**Comment by Melsteroni** [comment]
You and your log10 @oharac !

That is really cool.  I like it.

**Comment by jamiecmontgomery** [comment]
Good thinking Casey! 
![image](https://user-images.githubusercontent.com/6842510/75832845-1ba6f880-5d6c-11ea-8765-9311c03ed595.png)
